### ISSUE TITLE
SetLevel

### ISSUE THREAD

**Issue by SneakiAssassiN** [get-atlas/bot#21]
### Steps to reproduce

1. I type the command for setlevel and the username and level and it gives me an error
2. The error says "An error occured when executing the command that Atlas didn't understand. Sorry!"
3. I type a!setlevel @DreamWeaverXC 100
4. Then I get that error. Never had it happen before

### Expected behavior

It would set the levels just fine

### Actual behavior

Atlas won't set levels when typing in the commands

### Environment
- Server ID:
   I couldn't find a role matching your query! 
- Error messages (if any): 
```
An error occured when executing the command that Atlas didn't understand. Sorry!
```

### Additional information

![fixatlas1](https://user-images.githubusercontent.com/45867912/49986928-d3b17100-ff2e-11e8-94ce-56235b75f031.PNG)

![fixatlas1](https://user-images.githubusercontent.com/45867912/49986933-d90ebb80-ff2e-11e8-9464-00123128fdd3.PNG)
![fixatlas2](https://user-images.githubusercontent.com/45867912/49986943-dca24280-ff2e-11e8-822d-b57652487483.PNG)
![fixatlas3](https://user-images.githubusercontent.com/45867912/49986947-de6c0600-ff2e-11e8-9577-787c40fd9f23.PNG)
![fixatlas4](https://user-images.githubusercontent.com/45867912/49986983-02c7e280-ff2f-11e8-9ba5-4c1e1ca5128e.PNG)

<br />

### Additional checks

- [X] I have been able to reproduce the bug at least twice before submitting this bug report.
- [X] This bug does not exist on Trello.

**Comment by NotSylver** [comment]
Thanks for filling out a bug report!

What @itsdoddsy said is pretty much accurate. Atlas version 8 doesn't have these issues anymore, so this issue report is irrelevant to V8/Antares.
