### ISSUE TITLE
Now Playing doesn't displays properly

### ISSUE THREAD

**Issue by Sparks018** [get-atlas/bot#25]
### Steps to reproduce

1. Play a queue of atleast 2 songs
2. Use Now Playing Command
3. Use Queue command 

### Expected behavior

It should show "Author, Added By, Duration" for Now Playing embed.

It should show "Now Playing, Total Duration, In Queue, Up Next" for Queue embed

### Actual behavior

It shows "general.player.npEmbed.author, general.player.npEmbed.addedBy, general.player.npEmbed.duration" for the Now Playing embed

It shows "general.music.nowPlaying.name, totalDuration.name, inQueue.name, upNext.value"

### Environment
- Server ID: 481420038360793088
  
- Error messages (if any): 
```

```

### Additional information

![image](https://user-images.githubusercontent.com/45656721/50353368-1649fd80-056e-11e9-9edf-7808c6394d3c.png)
![image](https://user-images.githubusercontent.com/45656721/50353378-1ba74800-056e-11e9-80f8-86685d43b7b8.png)

<br />

### Additional checks

- [X] I have been able to reproduce the bug at least twice before submitting this bug report.
- [X] This bug does not exist on Trello.

**Comment by NotSylver** [comment]
Fixed in 8.0.17
