### ISSUE TITLE
Visual Glitches On Actions Module 

### ISSUE THREAD

**Issue by cykreet** [get-atlas/bot#27]
### Steps to reproduce
1. Head to Action module.
2. Change `Action One`'s delivery channel to anything other than `Invocation Channel`.

### Expected behavior
*Should* display the delivery channel of choice and *not* `Invocation Channel`.

### Actual behavior
Displays `Invocation Channel`.

### Environment
- Server ID: 365569515419074562
  
- Error messages (if any): 
```

```

### Additional information
Before:
![Before](https://user-images.githubusercontent.com/45258926/50486805-eaaa9580-09fb-11e9-9fb6-a68a6a7fe77e.png)
After:
![After](https://user-images.githubusercontent.com/45258926/50486805-eaaa9580-09fb-11e9-9fb6-a68a6a7fe77e.png)

Keep in mind this "bug" is purely a visual glitch and does not limit any functionality.

<br />

### Additional checks

- [x] I have been able to reproduce the bug at least twice before submitting this bug report. (Including confirmation from another admin, *node*)
- [x] This bug does not exist on Trello.

**Comment by itsdoddsy** [comment]
This is a dashboard issue, not a bot issue, and belongs on [`get-atlas/issues`](https://github.com/get-atlas/issues).
